name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Pack addon
        run: |
          mkdir dist
          zip -r dist/AnkiCC.ankiaddon . -x "venv/*" ".git/*" ".github/*" ".git*" "__pycache__/*" "dist/*" "requirements.txt"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

